Repository WhereGroup/profile_manager, pull requests merged in 2024-10, with the labels that each got.

#25 fix(ci): add i18n dependencies in a dedicated requirements
  .github/workflows/packager.yml
  requirements/translation.txt
Labels: ci-cd, dependencies

#24 feat(qdt export): initialization of qdt export
  CHANGELOG.md
  profile_manager/gui/interface_handler.py
  profile_manager/gui/mdl_profiles.py
  profile_manager/profile_manager.py
  profile_manager/profile_manager_dialog.py
  profile_manager/profile_manager_dialog_base.ui
  profile_manager/profiles/profile_copier.py
  profile_manager/profiles/profile_creator.py
  profile_manager/profiles/profile_editor.py
  profile_manager/profiles/profile_remover.py
  profile_manager/profiles/utils.py
  profile_manager/qdt_export/profile_export.py
  profile_manager/resources/i18n/plugin_translation.pro
Labels: enhancement, UI

#27 refacto(deadcode): rm unused files
  pb_tool.cfg
  pylintrc
Labels: enhancement

#29 update(plugin): add Oslandia and QDT to plugin's metadata
  profile_manager/metadata.txt
Labels: documentation

#31 update(ci): rm deprecated `set-output` command
  .github/workflows/packager.yml
Labels: ci-cd

#32 Switch dialog tabs to back sensible defaults
  profile_manager/profile_manager_dialog_base.ui
Labels: UI
