Repository WhereGroup/profile_manager, pull requests merged in 2025-03, with the labels that each got.

#49 fix(qdt profile): plugin_id should be an int
  profile_manager/profiles/utils.py
Labels: bug

#52 Documentation: complete contributing guide and publish to GitHub Pages using GitHub Actions
  .github/workflows/documentation.yml
  docs/conf.py
  docs/development/contribute.md
  docs/development/documentation.md
  docs/development/environment.md
  docs/development/history.md
  docs/index.md
  docs/static/dev_qgis_enable_plugin.png
  docs/static/dev_qgis_set_pluginpath_envvar.png
  docs/usage/installation.md
  profile_manager/metadata.txt
  requirements/documentation.txt
Labels: documentation, ci-cd, dependencies, UI

#58 add(tooling): dependabot configuration to track on dependencies update
  .github/dependabot.yml
Labels: tooling, ci-cd

#54 Tooling: add script to update translation
  docs/development/translation.md
  profile_manager/profile_manager.py
  profile_manager/profile_manager_dialog_base.ui
  profile_manager/resources/i18n/ProfileManager_de.ts
  profile_manager/resources/i18n/ProfileManager_fr.ts
  profile_manager/resources/i18n/ProfileManager_it.ts
  profile_manager/resources/i18n/plugin_translation.pro
  scripts/__init__.py
  scripts/generate_translation_profile.py
Labels: documentation, tooling, UI
